services:
  - type: web
    name: travel-services-bot
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: python3 bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_BOT_TOKEN
        value: ""
      - key: GEMINI_API_KEY
        value: ""
